data = [
    {"question": "The capital of France is Paris.", "answer": "True"},
    {"question": "The Earth is flat.", "answer": "False"},
    {"question": "Shakespeare wrote 'Romeo and Juliet'.", "answer": "True"},
    {"question": "Jupiter is the smallest planet in our solar system.", "answer": "False"},
    {"question": "Water boils at 100°C under standard pressure.", "answer": "True"},
    {"question": "Mount Everest is the tallest mountain on Earth.", "answer": "True"},
    {"question": "George Washington was the first President of the United Kingdom.", "answer": "False"},
    {"question": "The symbol for gold is Au.", "answer": "True"},
    {"question": "Guacamole is primarily made from tomatoes.", "answer": "False"},
    {"question": "The Pacific Ocean is the largest ocean.", "answer": "True"},
    {"question": "The capital of Japan is Tokyo.", "answer": "True"},
    {"question": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"question": "There are five continents on Earth.", "answer": "False"},
    {"question": "The square root of 64 is 8.", "answer": "True"},
    {"question": "Penicillin was discovered by Marie Curie.", "answer": "False"},
    {"question": "Ottawa is the capital of Canada.", "answer": "True"},
    {"question": "Mars is known as the Red Planet.", "answer": "True"},
    {"question": "Light travels faster than sound.", "answer": "True"},
    {"question": "The lion is known as the king of the jungle.", "answer": "True"},
    {"question": "Water is made up of two hydrogen atoms and one oxygen atom.", "answer": "True"},
    {"question": "Russia is the smallest country in the world.", "answer": "False"},
    {"question": "Neil Armstrong was the first person to walk on the moon.", "answer": "True"},
    {"question": "The Nile River is the longest river in the world.", "answer": "False"},
    {"question": "Rome is the capital of Italy.", "answer": "True"},
    {"question": "Oxygen is represented by the symbol O on the periodic table.", "answer": "True"},
    {"question": "A hexagon has eight sides.", "answer": "False"},
    {"question": "Vatican City is the smallest country in the world.", "answer": "True"},
    {"question": "Alexander Graham Bell invented the telephone.", "answer": "True"},
    {"question": "The Simpsons is the longest running TV show.", "answer": "True"},
    {"question": "Egypt is known for its pyramids.", "answer": "True"},
    {"question": "A football team consists of 11 players.", "answer": "True"},
    {"question": "The currency of the United States is the Euro.", "answer": "False"},
    {"question": "Mercury is the smallest planet in the solar system.", "answer": "True"},
    {"question": "1984 was written by Aldous Huxley.", "answer": "False"},
    {"question": "Canberra is the capital of Australia.", "answer": "True"},
    {"question": "Water freezes at 32°F.", "answer": "True"},
    {"question": "Plants absorb nitrogen from the atmosphere.", "answer": "False"},
    {"question": "Mandarin Chinese is the most spoken language in the world.", "answer": "True"},
    {"question": "Pizza was invented in the United States.", "answer": "False"},
    {"question": "An octopus has three hearts.", "answer": "True"},
    {"question": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"question": "The Sahara Desert is the largest desert in the world.", "answer": "False"},
    {"question": "The blue whale is the largest animal on Earth.", "answer": "True"},
    {"question": "Albert Einstein is considered the father of modern physics.", "answer": "True"},
    {"question": "The femur is the shortest bone in the human body.", "answer": "False"},
    {"question": "Madrid is the capital of Spain.", "answer": "True"},
    {"question": "A thermometer measures speed.", "answer": "False"},
    {"question": "William Shakespeare wrote the play 'Hamlet'.", "answer": "True"},
    {"question": "Sushi is primarily made from raw fish.", "answer": "False"},
    {"question": "The Great Barrier Reef is located in Australia.", "answer": "True"},
    {"question": "The Pacific Ocean is the deepest ocean.", "answer": "True"},
    {"question": "The Sahara Desert is located on the continent of Asia.", "answer": "False"},
    {"question": "Michelangelo painted the Sistine Chapel ceiling.", "answer": "True"},
    {"question": "Berlin is the capital of Germany.", "answer": "True"}
]

